{% set name = "zope.index" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope.index-{{ version }}.tar.gz
  sha256: 688ef079f8174664c19d8937094f09f7bd7b72be701784b655d94ee3daaf646c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - btrees >=4.4.1
    - persistent
    - python
    - setuptools
    - six
    - zope.interface

test:
  imports:
    - zope
    - zope.index
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zopefoundation/zope.index
  summary: Indices for using with catalog like text, field, etc.
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
