{% set name = "zope.index" %}
{% set version = "6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope.index-{{ version }}.tar.gz
  sha256: 99f1e041771add767428b12967c54bdb2152b17df9233d1671efabdfe01f6524

build:
  # no btrees on s390x
  skip: True  # [s390x]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - btrees >=4.4.1
    - persistent
    - python
    - six
    - zope.interface

test:
  imports:
    - zope
    - zope.index
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # The tests would normally use zope.testrunner (pip install
    # zope.testrunner; zope-testrunner --test-path=src) but we can use
    # pytest --pyargs zope.install to get most of the tests run
    - pytest --pyargs zope.index

about:
  home: https://github.com/zopefoundation/zope.index
  summary: Indices for using with catalog like text, field, etc.
  description: |
    The zope.index package provides several indices for the Zope
    catalog. These include:

    - a field index (for indexing orderable values),
    - a keyword index,
    - a topic index,
    - a text index (with support for lexicon, splitter, normalizer, etc.)
  license: ZPL-2.1
  license_file:
    - COPYRIGHT.txt
    - LICENSE.txt
  license_family: OTHER
  doc_url: https://zopeindex.readthedocs.io
  dev_url: https://github.com/zopefoundation/zope.index

extra:
  recipe-maintainers:
    - osamples
    - izahn
